# Generated by Django 3.2 on 2023-01-14 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=25, null=True)),
                ('order_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('q', 'Quotation'), ('d', 'Draft'), ('c', 'Confirmed'), ('so', 'Sale Order')], default='q', max_length=2)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_orders', to='customer.customer')),
            ],
            options={
                'verbose_name': 'SaleOrder',
                'verbose_name_plural': 'SaleOrders',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_lines', to='product.product')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_lines', to='sale.saleorder')),
            ],
            options={
                'verbose_name': 'SaleOrderLine',
                'verbose_name_plural': 'SaleOrderLines',
                'unique_together': {('sale_order', 'product')},
            },
        ),
    ]
