# Generated by Django 3.2 on 2023-01-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='devlivery_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
